### ISSUE TITLE
`pnpm install` fails

### ISSUE THREAD

**Issue by BrianG13** [julien-blanchon/arxflix#4]
Hi,

Thank you for sharing this cool tool! I find it super useful!

I am trying to install this repo, but I am getting an error when running `pnpm install` in the `frontend` folder:
````
Lockfile is up to date, resolution step is skipped
 ENOENT  not found: node

pnpm: not found: node
    at getNotFoundError (/snapshot/dist/pnpm.cjs)
    at Function.whichSync [as sync] (/snapshot/dist/pnpm.cjs)
    at getCommandAbsolutePathSync (/snapshot/dist/pnpm.cjs)
    at Object.sync (/snapshot/dist/pnpm.cjs)
    at getSystemNodeVersionNonCached (/snapshot/dist/pnpm.cjs)
    at getSystemNodeVersionNonCached (/snapshot/dist/pnpm.cjs)
    at checkPackage (/snapshot/dist/pnpm.cjs)
    at packageIsInstallable (/snapshot/dist/pnpm.cjs)
    at pkgAllDeps (/snapshot/dist/pnpm.cjs)
    at pkgAllDeps (/snapshot/dist/pnpm.cjs)
```

pnpm version: 9.4.0

Do you have any idea how can I fix this?

Thanks!!

**Comment by julien-blanchon** [comment]
Hi,

Look like `node` is not found.

Could you try `npm i pnpm --global`, to install pnpm globally

**Comment by BrianG13** [comment]
@julien-blanchon Thanks! Now it works.

I am using this thread instead of open a new one (if you want, I can do so).

Now, I am trying to create a video from a paper.. I am running the backend+frontend, running the entire steps..
I receive at the backend side:
```
INFO:     127.0.0.1:52152 - "POST /generate_assets/ HTTP/1.1" 200 OK
```

But I don't see any output has been written to the folders.

Also, at the website I see the follow (no video):
<img width="1158" alt="image" src="https://github.com/julien-blanchon/arxflix/assets/51123168/4d70c59f-f4b5-45ea-bbd6-fd7425caba43">

I found the temp folder that the audio, rich and json is written, but no video as well.

Can you help me? Thank you!

**Comment by BrianG13** [comment]
Update:

Maybe this will help, I don't see any frontend call that triggers /generate_video API. This is may be related?

**Comment by julien-blanchon** [comment]
You generate video without the UI with: https://github.com/julien-blanchon/arxflix/blob/main/run_manual.ipynb

**Comment by Flopsky** [comment]
@BrianG13  the issues is fixed now, let us know if it s good for you ?
