### ISSUE TITLE
functioning?

### ISSUE THREAD

**Issue by orrzohar** [julien-blanchon/arxflix#5]
I tried using your code, I reached:
<img width="1145" alt="image" src="https://github.com/julien-blanchon/arxflix/assets/108689663/e9b7de66-aee4-49f0-90fb-c06b33cd25f9">

when I navigated to http://localhost:3000

How am I supposed to run?

Best,
Orr

**Comment by orrzohar** [comment]
BTW when I install the dependency, I get
<img width="1066" alt="image" src="https://github.com/julien-blanchon/arxflix/assets/108689663/2c7830ae-887f-4db3-bdb4-61944ca98100">

**Comment by julien-blanchon** [comment]
Hey 👋, the UI is broken. Depending of your usecase if might be better to generate the video manually (with python directly).

What's your usecase ?

**Comment by orrzohar** [comment]
BTW my use case is that I want to create a video from a arxiv pdf
