### ISSUE TITLE
Error loading image with src: http://localhost:3000/public/static/LMNT_Logo_Full.png in generate_video block run_manual.ipynb

### ISSUE THREAD

**Issue by TharathDev** [julien-blanchon/arxflix#6]
<img width="1512" alt="Screenshot 2024-07-25 at 10 11 12 at night" src="https://github.com/user-attachments/assets/e0fe162e-61de-431e-a25a-af7548b79a82">
 any solution? Thanks

**Comment by julien-blanchon** [comment]
Hey your almost done as I see. 
Compiling the video with remotion is a tricky things. 
Look like your missing the LMNT logo, I've added it here (https://github.com/julien-blanchon/arxflix/blob/main/frontend/public/static/LMNT_Logo_Full.png). You might also need the LMNT.wav file (here https://github.com/julien-blanchon/arxflix/blob/main/frontend/public/static/LMNT.wav).

You need to place them in `./frontend/public/static`

**Comment by TharathDev** [comment]
> Hey your almost done as I see. Compiling the video with remotion is a tricky things. Look like your missing the LMNT logo, I've added it here (https://github.com/julien-blanchon/arxflix/blob/main/frontend/public/static/LMNT_Logo_Full.png). You might also need the LMNT.wav file (here https://github.com/julien-blanchon/arxflix/blob/main/frontend/public/static/LMNT.wav).
> 
> You need to place them in `./frontend/public/static`

thank you so much.

**Comment by julien-blanchon** [comment]
@TharathDev Did it end up working ?

**Comment by TharathDev** [comment]
> @TharathDev Did it end up working ?

YEAH
